# Generated by Django 4.1.4 on 2022-12-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='_id',
            new_name='id',
        ),
    ]
